Aggregation and bug fix
1. Aggregation of 3 pkl files
2. bug fix: use gpu if args.gpu > 0:
previously was gpu>=0 hence the --gpu 0 flag activates cuda training

* current error message:
Traceback (most recent call last):
  File "/Users/woodkong/Developer/ERSP/Trajectory_Prediction/attention_prediction.py", line 472, in <module>
    main()
  File "/Users/woodkong/Developer/ERSP/Trajectory_Prediction/attention_prediction.py", line 431, in main
    train(
  File "/Users/woodkong/Developer/ERSP/Trajectory_Prediction/attention_prediction.py", line 259, in train
    for i, (_input, target) in enumerate(train_loader):
  File "/Users/woodkong/opt/anaconda3/envs/ERSP/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/Users/woodkong/opt/anaconda3/envs/ERSP/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/Users/woodkong/opt/anaconda3/envs/ERSP/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/woodkong/opt/anaconda3/envs/ERSP/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/woodkong/Developer/ERSP/Trajectory_Prediction/lstm_utils.py", line 24, in __getitem__
    return (torch.FloatTensor(self.input_data[idx]),torch.FloatTensor(self.output_data[idx]))
TypeError: new(): data must be a sequence (got float)